### ISSUE TITLE
Should there be an option to exit rather than wait?

### ISSUE THREAD

**Issue by tdunning** [vtjnash/Pidfile.jl#8]
I have previously used an idiom where I would restart a process at intervals shorter than the completion time. Each restart would try to grab a pidfile ... on success, it would do any necessary work. On failure, it would simply exit since another process is doing the work.

In the current system, this would be easy to implement. The work function could be called if the pidfile is created on first try or is stale and then created, but not if these fail. It would be desirable to return some indicator of whether the function was called. A simple answer to that would be to return nothing if the lock failed and the result of the function otherwise.

In terms of implementation, a simple keyword flag could be added wait_for_lock with a default value of true. The while loop in the current code could be changed to wait_for_lock rather than true.

I think that all existing code would work without any change with this extension.

Any thoughts on this?

**Comment by tdunning** [comment]
I have implemented a version of this. It turns out to be incompatible with current tests to return nothing if the lock fails.

Currently implementing with a `PidLockFailed` exception instead.

**Comment by tdunning** [comment]
See pull request #9

**Comment by vtjnash** [comment]
Implemented in #9
